language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: trusty
sudo: required

script:
  - mkdir -p ../run-tests
  - cd ../run-tests
  - cmake --version
  - cmake $TRAVIS_BUILD_DIR/tests
  - ctest --output-on-failure
